
registry:
  hostname: registry.local
  image: registry:2
  name: registry
  ports:
   - "5000:5000"

cadvisor:
  hostname: cadvisor.local
  image: google/cadvisor:latest
  volumes:
   - /:/rootfs:ro
   - /var/run:/var/run:rw
   - /sys:/sys:ro
   - /var/lib/docker/:/var/lib/docker:ro
  ports:
   - "8080:8080"

alertmanager:
  hostname: prom_alert_manager.local
  image: prom/alertmanager
  command: -config.file=/alertmanager.conf
  volumes:
    - ./alertmanager/alertmanager.conf:/alertmanager.conf
  ports:
    - "9093:9093"

prometheus:
  hostname: prometheus.local
  image: prom/prometheus
  command: -alertmanager.url=http://prom_alert_manager:9093 -config.file=/etc/prometheus/prometheus.yml
  volumes:
   - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
   - ./prometheus/alert.rules:/etc/prometheus/alert.rules
  ports:
   - "9090:9090"
  links:
    - registry:registry.local
    - cadvisor:cadvisor.local
    - alertmanager:prom_alert_manager.local
